im:
  secret: 1111111111111111
  client: yan_xuan
spring:
  datasource:
    druid:
      url: jdbc:mysql://${my_ip}:3306/mall_im?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
